# 端口信息
server:
  port: 8080

# 数据库
#mysql:
#  url: "jdbc:mysql://localhost:3306";
#  username: "root";
#  password: "123456";

# 日志
logging:
  file:
    name: log/network.log
  pattern:
    file: "%d %-5level [%thread] %logger{36} - %msg%n"
    console: "%d %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: info
