# 端口信息
server:
  port: 8080

# 数据库
spring:
  # 配置邮件任务
  mail:
    username: 1065394472@qq.com # 你需要修改此处为你的QQ邮箱
    password: mrckipfthphabbag # 你需要修改此处为QQ邮箱独立密码
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  datasource:
    url: jdbc:mysql://localhost:3306/localhost?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Mark20030104
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志
logging:
  file:
    name: log/network.log
  pattern:
    file: "%d %-5level [%thread] %logger{36} - %msg%n"
    console: "%d %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: info

# 配置Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
